# Generated by Django 3.1.5 on 2021-03-22 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('text', models.TextField(max_length=400, verbose_name='Text')),
                ('delay', models.IntegerField(default=10, verbose_name='Delay')),
                ('duetime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Due time')),
            ],
        ),
    ]
